image: openjdk:21-jdk

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Compiling the code with Java 21..."
    - echo "Build complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests with Java 21..."
    - sleep 10
    - echo "Tests complete."
